### ISSUE TITLE
Uncaught exception in thread "main" caused by: java.lang.IllegalStateException: No compatible attachment provider is available

### ISSUE THREAD

**Issue by lilytoonk8** [ekulxam/TameableAxolotls#2]
### Mod version (NOT Minecraft version)

1.0.4+1.20.1-1.20.4

### A description of the issue

Fabric Loader presents the following error when trying to load the game:

[20:26:01] [main/ERROR]:
Uncaught exception in thread "main"
java.lang.ExceptionInInitializerError: null
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Unknown Source) ~[?:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:488) ~[fabric-loader-0.16.4.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:367) ~[fabric-loader-0.16.4.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:116) ~[fabric-loader-0.16.4.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.16.4.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.4.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.4.jar:?]
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:627) ~[net_bytebuddy_byte-buddy-agent-1.14.0-b1b9e6468c839d57.jar:?]
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:611) ~[net_bytebuddy_byte-buddy-agent-1.14.0-b1b9e6468c839d57.jar:?]
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:563) ~[net_bytebuddy_byte-buddy-agent-1.14.0-b1b9e6468c839d57.jar:?]
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:540) ~[net_bytebuddy_byte-buddy-agent-1.14.0-b1b9e6468c839d57.jar:?]
at survivalblock.tameable_axolotls.TameableAxolotlsAgent.<clinit>(TameableAxolotlsAgent.java:22) ~[tameable_axolotls-1.0.4+1.20.1-1.20.4.jar:?]
... 8 more

**Comment by lilytoonk8** [comment]
Nvm, fixed the issue! It seems I was using an outdated version of Java that didn't allow for the runtime installation of byte buddy.
